apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningManagement
  labels:
    app: learningManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningManagement
  template:
    metadata:
      labels:
        app: learningManagement
    spec:
      containers:
        - name: learningManagement
          image: username/learningManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5