---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderManagement
  labels:
    app: orderManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderManagement
  template:
    metadata:
      labels:
        app: orderManagement
    spec:
      containers:
        - name: orderManagement
          image: username/orderManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningManagement
  labels:
    app: learningManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningManagement
  template:
    metadata:
      labels:
        app: learningManagement
    spec:
      containers:
        - name: learningManagement
          image: username/learningManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningEvaluation
  labels:
    app: learningEvaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningEvaluation
  template:
    metadata:
      labels:
        app: learningEvaluation
    spec:
      containers:
        - name: learningEvaluation
          image: username/learningEvaluation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyPage
  template:
    metadata:
      labels:
        app: MyPage
    spec:
      containers:
        - name: MyPage
          image: username/MyPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Notification
  template:
    metadata:
      labels:
        app: Notification
    spec:
      containers:
        - name: Notification
          image: username/Notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: orderManagement
  labels:
    app: orderManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orderManagement


---


apiVersion: v1
kind: Service
metadata:
  name: learningManagement
  labels:
    app: learningManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: learningManagement


---


apiVersion: v1
kind: Service
metadata:
  name: learningEvaluation
  labels:
    app: learningEvaluation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: learningEvaluation


---


apiVersion: v1
kind: Service
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MyPage


---


apiVersion: v1
kind: Service
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Notification

